project:
  type: website
  output-dir: _site
  preview:
    port: 4200
  render:
    - "*.qmd"
  resources:
    - "img"
    - "img/web"
    - "img/logo"
    - "bib/"
    - "sessions/L1_images"

execute:
  freeze: auto

metadata-files:
  - _website.yml

highlight-style: pygments

qna:
  ipynb: question
  html: both
  pdf: question

format:
  html:
    theme: 
      - minty
      - css/casa-report.scss
      - css/casa-web.scss
    code-copy: true
    code-link: true
    #cover-image: cover.png
    toc: true
    toc-title: "On this page"
    toc-depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: true
  revealjs:
    logo: "/img/logo/full.svg"
    template-partials:
      - /inc/title-slide.html
    transition: none
    slide-number: false
    preview-links: auto
    theme:
      - css/casa-slides.scss # Must be valid *relative* path
    footer: "&copy; CASA &nbsp; | &nbsp; [ucl.ac.uk/bartlett/casa](https://www.ucl.ac.uk/bartlett/casa)"
filters:
 - code-visibility
lightbox: auto
title-slide-attributes:
    data-background-image: "/img/web/title-slide.png"
    data-background-size: stretch
    data-background-opacity: "0.08"
    data-background-color: "#4e3c56"
