---
format: html
date: last-modified
author: "Huanfa Chen"
title: "Getting Help"
lightbox:
  match: auto
  effect: fade
  desc-position: right
  loop: false
---

We *all* need help from time to time, and while we will *always* do our best to support you because we know that this module is hard for students who are new to quantitative modules or statistics, the best way to 'get help' will *also* always be taking steps to 'help yourself' first.

## How to Help Yourself 

Here are at least six things that you can do to 'help yourself':

- Make use of practical sessions--we can't help you if we don't know that you're struggling. Please talk to the lecturer or TAs during the pratical sessions.
- Use the dedicated **#casa0007_qm channel** on Slack --this provides a much richer experience than the Moodle Forum and should be your **primary means of requesting help** outside of scheduled teaching hours.
- Do the readings--regardless of whether we ask you questions in class about them (or not), the readings are designed to support the module's learning outcomes, so if you are struggling with a concept or an idea then please look to the week's readings! You should also review the [full bibliography](./references.qmd) while developing your thinking for the final project.
- Use [Google](https://google.co.uk) or [Stack Overflow](https://stackoverflow.com/questions/tagged/python)--as you become a better programmer you'll start to understand how to frame your question in ways that produce the right answer right away, but whether you're a beginner or an expert Stack Overflow is your friend.
- Sign up for online classes--there are lots of plausible online classes on [LinkedIn course](https://www.linkedin.com/learning/) or [Coursera ](https://www.coursera.org/). Please check the reviews before you take an online module.